#!/bin/bash
#set -e # abort if there is an issue with any build

# Create temporary content to evade errors
touch /tmp/vm_encrypted_pass
mkdir content

# Increment build number
n=38;#build number
next_n=$[$n+1]
sed -i "/#build number$/s/=.*#/=$next_n;#/" ${0}
printf '%s' $n > content/build.md

# Run Step Builds
packer build -only='step-1.null.encrypted-pass' .
packer build -only='step-2.file.meta-data' .

echo "================= build info ======================="
cat content/meta-data | jq
echo "===================================================="

packer build -only='step-2.file.user-data' .
packer build -only='step-3.vsphere-iso.linux-ubuntu-server' .

# Remove residual files
CONTENT=./content
[ -d $CONTENT ] && rm -rf $CONTENT
FILE=/tmp/vm_encrypted_pass
test -f $FILE && rm $FILE
