#!/bin/bash

# Usage: packer-build -var-file=consul.pkrvars.hcl
# for latest tag : ./packer-build -var-file=consul.pkrvars.hcl --production #or -p
#set -e # abort if there is an issue with any build

# Create temporary content to evade errors
touch /tmp/vm_encrypted_pass
mkdir content

# Increment build number
n=73;#build number
next_n=$[$n+1]
sed -i "/#build number$/s/=.*#/=$next_n;#/" ${0}

if [[ "${2}" == "-p" || "${2}" == "--production" ]]; then
    printf '%s' "latest" > content/build.md
else
    printf '%s' $n > content/build.md
fi

# Run Step Builds
packer build -only='step-1.null.encrypted-pass' ${1} .
packer build -only='step-2.file.meta-data' ${1} .

echo "================= IMAGE INFO ======================="
cat content/meta-data | jq
echo "===================================================="

packer build -only='step-2.file.user-data' ${1} .
packer build -only='step-3.vsphere-iso.linux-ubuntu-server' ${1} .

# Remove residual files
CONTENT=./content
[ -d $CONTENT ] && rm -rf $CONTENT
FILE=/tmp/vm_encrypted_pass
test -f $FILE && rm $FILE
